### ISSUE TITLE
create a README.md

### ISSUE THREAD

**Issue by necronet** [UPNicaragua1024/Coding-Lab-Nicaragua-2018#3]
Create an README.md that will:

- List all the project with the author of the girl
- A summary of granada girl that code.
- Be well formatted markdown file.

**Comment by ReenaSingh07** [comment]
can i work with this?

**Comment by necronet** [comment]
Sure @ReenaSingh07, although as a disclaimer this is not a particular challenging project from a developer perspective, we're just trying to use it as a showcase boilerplate of project of an initiative in Nicaragua. Get more information at https://www.upnicaragua.org/
